### ISSUE TITLE
Generate Data from Estimated PDEs

### ISSUE THREAD

**Issue by numerical-newbee** [snagcliffs/PDE-FIND#4]
Hey, thank you a lot for opensourcing the code and data!
Could you also give some suggestions on regenerating the data sequence, given the estimated PDE in a complex form, such as:
u_t = 0.1*u_xx + 0.2*u_xy + 0.3*u_yy + 0.4*u*u_x + 0.5*u^2*u_yy 
For some real data sequence, it looks like some reaction/diffusion dynamics there, but unlike the simulation, we do not have the ground-truth equations. It would be cool if we can  accurately regenerate the video from the estimated PDEs and compare it with the real data. For example, in your Reaction-diffusion matlab code, you use the Fourier mesh grid (K22) for the Laplace operator.
Could you please give more suggestions for PDEs in a general form like the above one?

**Comment by TomBolton** [comment]
I too have this issue when applying PDE-FIND to observations of sea surface temperature, where you know what terms should appear (advection, laplacian diffusion), but the exact 'truth' is unavailable. 

To help with this, I added a few lines of code to calculate the coefficient of determination (R-squared) in the TrainSTRidge() function.

```python

# R2 coefficient of determination:
# 1 = perfect regression 
# 0 = as good as expected value, which is pretty useless 
# <0 means arbitrarily bad...
        
numer = np.sum( np.square( TestY - TestR.dot(w) ) )
denom = np.sum( np.square( TestY - np.mean( TestY ) ) )
        
R2 = 1 - numer / denom

```
If R2 is close to or less than zero, then you know that the resulting PDE is explaining very little of the variability present in the dataset, and should not be trusted. For example, with observations of SST in the North Atlantic, I was finding the following PDE

dT/dt + 0.01 v dT/dy = 0,

which kinda makes sense that latitudinal advection dominates. However, R2 ~ 0.06, so it is only capturing a tiny fraction of the variance. Therefore the above PDE is not useful and likely not correct. I think I'm limited by the temporal resolution of my dataset (weekly) in this particular case, even when sampling 5000 points in space and 300 time-slices.

**Comment by numerical-newbee** [comment]
That's a good point on model selection. There are follow-up work on model selection (http://rspa.royalsocietypublishing.org/content/473/2204/20170009). On this point, regenerating movies from estimated equations may not be meaningful, since we can use the numerical derivatives to calculate the degree of fitness.
