### ISSUE TITLE
Error in Reaction diffusion System

### ISSUE THREAD

**Issue by SayedAIrfan** [snagcliffs/PDE-FIND#7]
I am trying to run the reaction diffusion system file I am getting the following errors 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-12-7842b91df2e6> in <module>
     29     # time derivatives
     30 
---> 31     ut[p] = PolyDiffPoint(U[x,y,t-(Nt-1)/2:t+(Nt+1)/2], np.arange(Nt)*dt, deg, 1)[0]
     32 
     33     vt[p] = PolyDiffPoint(V[x,y,t-(Nt-1)/2:t+(Nt+1)/2], np.arange(Nt)*dt, deg, 1)[0]

TypeError: slice indices must be integers or None or have an __index__ method
```
 
could you please help me to resolve the problem. 

Best regards

**Comment by danie906** [comment]
It appears that the way you are calculating the indices is creating floating point values instead of integers (or logical).  My first guess would be `t-(Nt-1)/2` and `t+(Nt+1)/2`.  The fastest, although not guaranteed accurate resolution is to use `round()`.

**Comment by SayedAIrfan** [comment]
Hi Danie, Thank for the response. I did not change the code from the original file.  

I tried to use the round() getting the same error. 
can you help me how to incorporate the t as a time not an index in the code.

**Comment by snagcliffs** [comment]
Hi Sayed,

This might be due to using a different version of python.  The code was originally written for python 2, where ratios of integers are rounded and stored as integers.  In python 3, they are treated as floats and round() maintains that type.  Using int((Nt+1)/2) might fix it.

Hope that helps.

**Comment by SayedAIrfan** [comment]
I have tried using int I am getting the index error. 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I have tried to convert the code both PDE_FIND and Reaction diffusion from python 2 to python 3 still no help. 
Thanking you in advance.

Best regards 
Irfan

**Comment by snagcliffs** [comment]
It seems like one of t-(Nt-1)/2 and t+(Nt+1)/2 is not an integer.  Can you print out what they are?

**Comment by BMP-TUD** [comment]
Hi all, 

I have encountered the same problem, and I tried using int((Nt-1)/2) which i think should work, but now the actual problem has moved to the PolyDiffPoint function in Line 187: 


```
  File "...\PDEFIND\reaction_diffusion.py", line 115, in <module>
    ut[p] = PolyDiffPoint(U[x,y,t-int((Nt-1)/2):t+int((Nt+1)/2)], np.arange(Nt)*dt, deg, 1)[0]

  File "...PDEFIND\PDE_FIND.py", line 187, in PolyDiffPoint
    derivatives.append(poly.deriv(m=d)(x[index]))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

In my opinion, the index in the function is not an integer but has the value 255.5 making it of type float. Has it worked for before? 

```
 if index == None: index = (n-1)/2

    # Fit to a Chebyshev polynomial
    # better conditioned than normal polynomials
    poly = np.polynomial.chebyshev.Chebyshev.fit(x,u,deg)
    
    # Take derivatives
    derivatives = []
    for d in range(1,diff+1):
        derivatives.append(poly.deriv(m=d)(x[index]))
        
    return derivatives
```

What are Your thoughts on that? Thank you for your help, 
Best regards, 
Bartosz

**Comment by Song-kxin** [comment]
> Hi all,
> 
> I have encountered the same problem, and I tried using int((Nt-1)/2) which i think should work, but now the actual problem has moved to the PolyDiffPoint function in Line 187:
> 
> ```
>   File "...\PDEFIND\reaction_diffusion.py", line 115, in <module>
>     ut[p] = PolyDiffPoint(U[x,y,t-int((Nt-1)/2):t+int((Nt+1)/2)], np.arange(Nt)*dt, deg, 1)[0]
> 
>   File "...PDEFIND\PDE_FIND.py", line 187, in PolyDiffPoint
>     derivatives.append(poly.deriv(m=d)(x[index]))
> 
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> ```
> 
> In my opinion, the index in the function is not an integer but has the value 255.5 making it of type float. Has it worked for before?
> 
> ```
>  if index == None: index = (n-1)/2
> 
>     # Fit to a Chebyshev polynomial
>     # better conditioned than normal polynomials
>     poly = np.polynomial.chebyshev.Chebyshev.fit(x,u,deg)
>     
>     # Take derivatives
>     derivatives = []
>     for d in range(1,diff+1):
>         derivatives.append(poly.deriv(m=d)(x[index]))
>         
>     return derivatives
> ```
> 
> What are Your thoughts on that? Thank you for your help,
> Best regards,
> Bartosz

I have met the same problem,  and I tried the same step but fail. Has your previous problem been solved now？

**Comment by BMP-TUD** [comment]
Hi, yes I fixed it. The index in the function is seen as a float, because Python3 interprets integers that are divided by something as a float. You have to set the index expression to int: int(n-1/2) ... in the function. And you have to do the above mentioned step. 

Greetings,
Bartosz
