### ISSUE TITLE
How to generate data for Burgers, KS, Schrodinger, NLS

### ISSUE THREAD

**Issue by Jack36lee** [snagcliffs/PDE-FIND#8]
Hello Rudy, I am interested in the PDE-FIND and want to see what will happen for PDE-FIND when the space and time of the PDEs are changed. I have tried Python and Matlab (pdetool) to simulate Burgers, KS, Schrodinger and NLS equations, but my results seem to be incorrect. What software/programming did you use to generate the data? And could you please show how to generate data for Burgers, KS, Schrodinger and  NLS equations? Thank you!

**Comment by snagcliffs** [comment]
Hi Jack, with the exception of Navier-Stokes and Kuramoto-Sivashinsky, all of the datasets were made using ode45 and the fft to evaluate derivatives.  We solved KS using a method meant for stiff PDEs described in the paper below.

Aly-Khan Kassam and Lloyd N Trefethen.  Fourth-order time-stepping for stiff pdes.  SIAM Journal on Scientific Computing, 26(4):1214–1233, 2005
