### ISSUE TITLE
NavierStokesExample Plotting w u v didn't converge after SVD decomposition

### ISSUE THREAD

**Issue by 130706472** [snagcliffs/PDE-FIND#9]
Hello, I have run the ibpm generator with the von_karman.sh conditions. I imported 151 timesteps to the Navier Stokes Example code, but the plotted value looks different from the one in the example you posted. Mine plots are not converging and showing a decreasing pattern. Therefore, I wasn't able to obtain a clean identified N-S equation. Do you know how to deal with this problem? Thanks!!
![Figure 2021-05-27 011557](https://user-images.githubusercontent.com/42524625/119791592-ce8bd680-be89-11eb-8539-fe17b4babc7f.png)

**Comment by snagcliffs** [comment]
Hi.  This does look off.  I re-ran the von_karman.sh script and got the correct singular value spectrum so am not sure what is going wrong.  The current script only writes 101 files.  Did you change it to 151?  It might also be worth checking ibpm.force to verify that the fluid solver is working correctly.  The third column should be oscillating around ~1.36 and the fourth about zero with a maximum amplitude of ~0.337.  If these are different than the problem is likely in the installation of the solver.

**Comment by 130706472** [comment]
I'm obtaining the correct pattern of the oscillation for froce.ibpm data. 
![force oscillation](https://user-images.githubusercontent.com/42524625/119898530-d5046780-bef6-11eb-8f3b-3d83772c5f6a.png)

The reason that I import 151 steps is that the for loop bellow generates t up to 151, and it's exceeding the index if I import only 101 steps. The loop that's reading points would have an index error because t is exceeding 101, so I thought that you imported 151 steps of data.
`
for p in range(num_xy):
    x = np.random.choice(np.arange(boundary_x,n-boundary_x),1)[0]
    y = np.random.choice(np.arange(boundary,m-boundary),1)[0]
    for t in range(num_t):
        points[count] = [x,y,2*t+12]
        count = count + 1`

Moreover, my force document has the correct oscillating patterns. What I'm curious about is the environment you run this python example. When I implement svd(), it belongs to the package NumPy, and it's not called as a method in the example you posted. So I was wondering if the svd() function is not from the Numpy Package.

**Comment by snagcliffs** [comment]
The forces look good and it also looks like you already switched von_karman.sh to run for more than 1000 steps (nsteps should be 1500, not 1000, to get 151 snapshots).  I'm using the svd implemented in numpy - this is sloppy code on my part as it should have been called as np.linalg.svd, but has the same result.  Are you using the code from /Datasets/von_karman/Loading ibpm output.ipynb to load the .plt files?

**Comment by 130706472** [comment]
Hi, I was using the same code to load out the results. I've succesfully obtaind the sparsed N-S equation, but the svd() plot still looks weird and I couldn't find the error. Thanks for providing these helpfull informations! Moreover, would you like me to edit some codes in the N-S example? since I was able to run it initially, and it might be helpful for people who want's to try this.

**Comment by 130706472** [comment]
Hi, I'm also interested in whether the PDE-FIND algorithm would be able to identify the Navier Stokes equation in Reynolds number other than 100. I have generated flowfield at Re200 using ibpm starting with ibpm00000.bin file with 16500 timesteps. Then I imported plt files as the ibpm-load does. However, I wasn't able to obtain a sparse identified N-S equation after running this code. Are there any parameters that I have to modify in order to predict other types of flow fields? Thanks!!

**Comment by snagcliffs** [comment]
In theory the method should work for any Reynolds number, but may fail due to a number of reasons.  It could be that the parameters need to be changed, or timestep in the data.  There are also a number of newer sparse regression methods for PDEs that perform better than the one in this paper/github.
